class DatabaseModel():
    def getID(self):
        return 1
    def database(self):
        return 1
    def table(self):
         return 1
    def toMap(self):
        return 1
    def DatabaseModelFromMap(self):
        return 1
